Algoritmo "troca de valores "
// 
// Troca de valores
// Autor: Marcos Dias Conceição
Var
A,B,C: inteiro

Inicio
A <- 12
B <- 20

escreval("O valor de A é",A)
escreval ("O valor de B é",B)

C<- A
A<- B
B<- C
escreval()
escreval("==============================-==============================")
escreval()
escreval ("O valor de A é",A)
escreval ("O valor de B è",B)

Fimalgoritmo